# -*- coding: utf-8 -*-
"""Untitled15.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-oXDcBEEjcqW786IaaFyAztQeKrvuxnh
"""

#whether a number is in range
def Range(n):
  if n in range(1,9):
    print("number is in inside")
  else:
    print("number is in outside")  
Range(8)

