# -*- coding: utf-8 -*-
"""Untitled15.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-oXDcBEEjcqW786IaaFyAztQeKrvuxnh
"""

#max of three numbers
def big(a,b,c):
  if(a>b) and (a>c):
    print("a is greater")
  elif(b>a) and (b>c):
    print("b is greater")
  else:
    print("c is greater")
big(2,4,6)